### ISSUE TITLE
Bump Allocation

### ISSUE THREAD

**Issue by YorickPeterse** [rust-hosted-langs/book#4]
We need a chapter on allocating memory. I'm specifically thinking of bump allocation because:

1. It's super easy to implement
2. It delivers good performance
3. It can support concurrent and atomic operations, though you may still need locking in certain cases (e.g. when requesting a new arena to allocate into)

**Comment by pliniker** [comment]
Re: `alloc` - I opened #9 for going over options.

**Comment by pliniker** [comment]
Basic single-threaded bump allocator :heavy_check_mark:
