### ISSUE TITLE
Obtaining blocks of memory

### ISSUE THREAD

**Issue by pliniker** [rust-hosted-langs/book#9]
There are options in Rust, depending on circumstances and requirements:

Nightly only:
- use of experimental `alloc` features on nightly Rust
  - access the global allocator https://doc.rust-lang.org/nightly/alloc/alloc/struct.Global.html
  - allows specifying block alignment
  - cross-platform

Stable:
- `libc::posix_memalign()` (and equivalent on other platforms that I'm not familiar with)
  - https://github.com/jonas-schievink/aligned_alloc.rs
  - allows specifying block alignment
  - platform-specific solutions
- using a `Vec` as a `*mut u8` 
  - https://github.com/reem/rust-memalloc
  - no way to specify block alignment

**Comment by pliniker** [comment]
It would be nice to stick with stable Rust for as long as possible for broader usability of example code, but that would leave us with lesser allocation options.

**Comment by pliniker** [comment]
Actually, this should be a chapter and the outcome could be a crate that provides an api like `new_block(size) -> Block` (where align==size) and `drop_block(Block)` where internally it uses whatever is available when compiled on nightly or stable.

I think I'll work a draft of this (chapter plus crate) and see what it looks like.

**Comment by pliniker** [comment]
Here's a rough draft of a possible chapter covering this topic with the end goal being Immix, so focusing on block-aligned-blocks of memory.

https://pliniker.github.io/book/master/chapter-blocks.html

I'm not 100% sure on the book source format, using `{{#include ../blockalloc/src/lib.rs:nnn:mmm}}`

* it's inconvenient to make changes to the code, then have to adjust the line numbers for every `#include`
* on the one hand, the point is a book, so the Rust code and the markdown are interlinked - changing the code should force a review of the book
* the alternative is copying and pasting relevent sections of Rust into the markdown

@madmalik @YorickPeterse @mattgreen @CAD97  I would appreciate any thoughts on this!

I have a Windows machine available so I will get around to experimenting with allocation there; it's been a very busy 3 weeks for me and I haven't had much time for this. Hopfully I'll be able to make better progress now.

**Comment by pliniker** [comment]
>> There are plenty of case where we will not care about block alignment. For example, providing arenas for immutable interned objects. In such a case, the only guarantee needed is that the objects don't ever move and can be reliably freed at the end of the arena life.
>
> ......... no, for any type T, it needs to be aligned at std::mem::align_of::<T>() to take a reference to it. I suppose that can be handled at a different level, but honestly, using typed arenas isn't too bad.

You're right, of course.  This section is badly worded and very incomplete.  Given that in this chapter I'm mostly concerned with block-size-aligned memory blocks, this may not belong in here at all.  It may be better placed and correctly written in an introductory summary chapter mentioning typed arenas.

> Probably we'd be better off with `type BlockPtr = std::ptr::NonNull<u8>` than `*mut u8`.

:+1: 

>> Where:
>> * parameter size must be a power of two
>
> Then either assert! it, make fn new unsafe, or take the exponent and do 2 << param.

Checking the parameter would be the right approach.  I was relying on the underlying system/rust call to do the validation but it definitely makes more sense to not do that across differently-behaving underlying APIs given the specific input requirement.

What really threw me off with `std::alloc::Global` API is the return value of `fn alloc()`.  After a bit more careful reading, I realized that `Global` implements both `std::alloc::GlobalAlloc` (as you linked to) _and_ [std::alloc::Alloc](https://doc.rust-lang.org/nightly/core/alloc/trait.Alloc.html) which _[both](https://doc.rust-lang.org/nightly/src/alloc/alloc.rs.html#74-111)_ have a `fn alloc()`.  Nightly rustc insists I use the `Alloc::alloc()` version by default, which returns a `Result<std::ptr::NonNull, AllocErr>`.  It's the use of `AllocErr` that originally confused me though I it seems my mistake was looking at [out-of-date](https://doc.rust-lang.org/core/heap/enum.AllocErr.html) documentation.

Going to make changes...

**Comment by YorickPeterse** [comment]
@pliniker 

> it's inconvenient to make changes to the code, then have to adjust the line numbers for every #include

What if we make every example a valid program on itself? That means that instead of something like this:

```rust
let foo = bar();
```

The snippet would look like this:

```rust
use something::bar;

fn main() {
  let foo = bar();
}
```

I realise this might make them more verbose, but it removes the need for having to change the `include` directives` whenever the source files are changed.

**Comment by pliniker** [comment]
@CAD97 thanks for your feedback, very appreciated. I've made hopefully appropriate adjustments:

- https://pliniker.github.io/book/master/chapter-blocks.html
- https://github.com/pliniker/book/commit/4e5b76ec2583fb762d1918e6ee9391fa54475e3a

@YorickPeterse :thinking: could get _very_ verbose and seems likely to lead to a lot of copying and pasting  of snippets/sub-snippets especially when global changes are made?

**Comment by pliniker** [comment]
Added some hopefully accurate and useful detail on alignment
https://pliniker.github.io/book/master/chapter-what-is-alloc.html#alignment
